### ISSUE TITLE
Test TDF website

### ISSUE THREAD

**Issue by marektucek** [closerdao/closer-ui#70] opened 2023-03-07 11:58 UTC
http://dev.traditionaldreamfactory.com

**Comment by marektucek** [comment] 2023-03-07 12:42
![Image](https://user-images.githubusercontent.com/94184807/223425144-c38e6cd2-c26e-4f04-8596-08adbe1b3f9f.png)

after registration and connecting wallet

**Comment by marektucek** [comment] 2023-03-07 12:45
![Image](https://user-images.githubusercontent.com/94184807/223425880-65ced0d3-cd0e-417c-8b30-69bb7f221ae4.png)

Accomodation is empty.

**Comment by marektucek** [comment] 2023-03-07 12:48
![Image](https://user-images.githubusercontent.com/94184807/223426547-77b2f177-4aaa-438e-b6a2-7a83d78b9d6a.png)


somehow doesn't fit my screen (chrome, 13" macbook air)

**Comment by marektucek** [comment] 2023-03-07 12:53
![Image](https://user-images.githubusercontent.com/94184807/223426928-fe8c2aaf-8730-43d2-a751-4f09aaf2e32d.png)

opening the invite link - missing image.

**Comment by marektucek** [comment] 2023-03-07 12:54
![Image](https://user-images.githubusercontent.com/94184807/223427615-30a25694-d349-485f-9dd1-b31833765747.png)

when I registered, I was automatically signed in (correctly), but the page doesn't reflect this.

**Comment by closerearth** [comment] 2023-03-07 13:39
We need to port /listings

**Comment by b-triz** [comment] 2023-03-09 11:41
<img width="744" alt="Screenshot 2023-03-09 at 11 39 52" src="https://user-images.githubusercontent.com/95632589/224012713-19ab2fab-a7e7-4ceb-abc2-f7991d039f35.png">

Instead of 'Apply' (apply for what in particular' lets do 'Want to know more?'

**Comment by b-triz** [comment] 2023-03-09 11:45
I created a new account (with a new e-mail) and was forwarded to home page (https://dev.traditionaldreamfactory.com/)

Let's decide what comes after I create an account, could be
- filling your profile
- thank you, we'll get back to you to book a call soon

**Comment by b-triz** [comment] 2023-03-09 11:46
<img width="751" alt="Screenshot 2023-03-09 at 11 44 55" src="https://user-images.githubusercontent.com/95632589/224013777-6adc8a88-6cab-46f0-9181-39ece6f78e7a.png">

Settings 
- Add e-mail change
- Password change
- Name change
- Upload my picture
- delete my account

**Comment by b-triz** [comment] 2023-03-09 11:47
<img width="694" alt="Screenshot 2023-03-09 at 11 46 10" src="https://user-images.githubusercontent.com/95632589/224014030-45b2aab2-7f8c-4a6f-97c9-eb91d88cba12.png">

No listings show when I try to book, is it because no listing have been created or is there a bug?

**Comment by b-triz** [comment] 2023-03-09 11:49
<img width="352" alt="Screenshot 2023-03-09 at 11 47 31" src="https://user-images.githubusercontent.com/95632589/224014322-36523456-e369-43b0-8d09-81fc0635d125.png">

When I sign up (just created an account) I'm immediatly registered as a 'member'
not sure what this means in backend, but at this point, new sign ups should be a 'guest' user

**Comment by b-triz** [comment] 2023-03-09 11:52
<img width="709" alt="Screenshot 2023-03-09 at 11 50 45" src="https://user-images.githubusercontent.com/95632589/224015031-f9141f6f-9a68-4615-a8da-f242d865dffc.png">

Lets add an 'Events' button here (or somewhere else) - currently folks only see events if they open the menu

**Comment by b-triz** [comment] 2023-03-09 11:53
<img width="381" alt="Screenshot 2023-03-09 at 11 51 41" src="https://user-images.githubusercontent.com/95632589/224015234-91eee1df-61ff-42f4-8583-232f02b4dde8.png">

Sign in to get the most out of TDF ?

**Comment by b-triz** [comment] 2023-03-09 11:57
<img width="754" alt="Screenshot 2023-03-09 at 11 54 18" src="https://user-images.githubusercontent.com/95632589/224015787-71de25c9-3aa0-476a-8bc3-669876dda8fc.png">

When I click my picture in the menu, I go to my profile (background on the picture)
- lets add a button on the menu box next to my name that shows that I can actually see/edit my profile (I pressed the picture with curiosity, didn't know if smth would happen)
- this user's page could be the page we redirect folks to when they sign up

**Comment by marektucek** [comment] 2023-03-09 12:18
![Image](https://user-images.githubusercontent.com/94184807/224020773-218c24ad-7549-4905-9b2b-447edc4379c4.png)

tried to deselect the weekly summary email and save, this error happened

**Comment by marektucek** [comment] 2023-03-09 12:49
![Image](https://user-images.githubusercontent.com/94184807/224027462-2816111c-8cf6-4e88-9a5d-a577eac995b4.png)

when signing up, if an error is triggered because passwords dont match or dont meet requirements, any further character added to the password line instantly triggers this page.
https://dev.traditionaldreamfactory.com/signup?back=/token-sale

[bug]

**Comment by marektucek** [comment] 2023-03-09 12:51
when registering, the line for phone number accepts letters.

[bug]

**Comment by marektucek** [comment] 2023-03-09 13:01
![Image](https://user-images.githubusercontent.com/94184807/224030735-06533e25-2762-4fb8-a38e-9a52bc40569d.png)

"meet 'myself' at:" doesnt make any sense here, should be "My events:" when it's the same user that's currently logged in

[modify]

**Comment by marektucek** [comment] 2023-03-09 13:10
![Image](https://user-images.githubusercontent.com/94184807/224032884-a24bc847-fea7-44c0-bfec-065f9973c3f8.png)

when I register a new account and use the same wallet as I use for another account, it only shows this error and I dont know whats happening.

[bug]

**Comment by sorokinvj** [comment] 2023-03-12 15:20
> <img alt="Screenshot 2023-03-09 at 11 44 55" width="751" src="https://user-images.githubusercontent.com/95632589/224013777-6adc8a88-6cab-46f0-9181-39ece6f78e7a.png">
> 
> Settings
> 
> * Add e-mail change
> * Password change
> * Name change
> * Upload my picture
> * delete my account
> 
> [new feature]

we should create a ticket for that @marektucek

**Comment by sorokinvj** [comment] 2023-03-12 15:21
> <img alt="Screenshot 2023-03-09 at 11 47 31" width="352" src="https://user-images.githubusercontent.com/95632589/224014322-36523456-e369-43b0-8d09-81fc0635d125.png">
> 
> When I sign up (just created an account) I'm immediatly registered as a 'member' not sure what this means in backend, but at this point, new sign ups should be a 'guest' user
> 
> [modify]

we should create a ticket for that @marektucek

**Comment by sorokinvj** [comment] 2023-03-12 15:21
> <img alt="Screenshot 2023-03-09 at 11 50 45" width="709" src="https://user-images.githubusercontent.com/95632589/224015031-f9141f6f-9a68-4615-a8da-f242d865dffc.png">
> 
> Lets add an 'Events' button here (or somewhere else) - currently folks only see events if they open the menu [modify]

we should create a ticket for that (I need @daneelminev input)

**Comment by sorokinvj** [comment] 2023-03-12 15:56
> ![Image](https://user-images.githubusercontent.com/94184807/224020773-218c24ad-7549-4905-9b2b-447edc4379c4.png)

cannot reproduce @marektucek, please take a look again here - [traditionaldreamfactory-git-fix-issue-70-closerdao.vercel.app](https://traditionaldreamfactory-git-fix-issue-70-closerdao.vercel.app/)
it you can reproduce it and we think its important - lets create a separate bug ticket for that and I will investigate it again

**Comment by sorokinvj** [comment] 2023-03-12 16:31
Dear all, what I could fix easily - I fixed in [traditionaldreamfactory-git-fix-issue-70-closerdao.vercel.app](https://traditionaldreamfactory-git-fix-issue-70-closerdao.vercel.app/) - please check again.

What I didn't fix: 
- all new features requests
- "Sign in to get the most out of Closer" in many (I will create a ticket for that)
- Wrong wallet address bug (created a ticket for that)

**Closed** 2023-03-23 13:28 UTC
Labels: bug
